import React, { useMemo } from "react";
import Section from "../components/ui/Section.jsx";
import { BarSeries, LineChartM, RadarBundle } from "../components/charts/ChartFrame.jsx";
import { TrendingUp, Clock, Leaf, Gauge, Brain } from "lucide-react";

const HORIZONS = ["5m", "10m", "30m"];

export default function PredictionPage({ prediction, last }) {
  const p = prediction || {};
  const data = useMemo(() => HORIZONS.map((h) => ({
    horizon: h,
    queue: p[h]?.queue ?? 0,
    congestion: p[h]?.congestion ?? 0,
    delay: p[h]?.delay ?? 0,
    co2: p[h]?.co2 ?? 0,
    fuel: p[h]?.fuel ?? 0,
    travel: p[h]?.travel ?? 0,
  })), [p]);

  const radar = useMemo(() => ([
    { metric: "Queue", value: data[1]?.queue ?? 0 },
    { metric: "Congestion", value: data[1]?.congestion ?? 0 },
    { metric: "Delay", value: data[1]?.delay ?? 0 },
    { metric: "CO₂", value: (data[1]?.co2 ?? 0) * 100 },
    { metric: "Fuel", value: (data[1]?.fuel ?? 0) * 50 },
    { metric: "Travel", value: data[1]?.travel ?? 0 },
  ]), [data]);

  return (
    <div className="space-y-4">
      <header>
        <h1 className="text-[22px] font-semibold">Prediction</h1>
        <p className="text-[12px] text-slate-400">5 / 10 / 30-minute forecasts generated by the Prediction Agent (linear-trend forecaster).</p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {HORIZONS.map((h, i) => {
          const v = p[h] || {};
          return (
            <div key={h} className="glass p-4">
              <div className="flex items-center justify-between">
                <span className="text-[11px] uppercase tracking-[0.18em] text-slate-400">Horizon</span>
                <span className="pill-cyan">{h}</span>
              </div>
              <div className="text-[28px] font-semibold mt-1">
                <Confidence value={v.confidence ?? 0} />
              </div>
              <div className="text-[11px] text-slate-400">moderated by time horizon</div>
              <div className="mt-3 space-y-1 text-[12px]">
                <KV icon={<Gauge className="h-3 w-3 text-neon-cyan" />} label="Queue" value={v.queue?.toFixed(1)} />
                <KV icon={<TrendingUp className="h-3 w-3 text-neon-violet" />} label="Congestion" value={`${v.congestion?.toFixed(1)}%`} />
                <KV icon={<Clock className="h-3 w-3 text-neon-amber" />} label="Delay" value={`${v.delay?.toFixed(1)}s`} />
                <KV icon={<Leaf className="h-3 w-3 text-neon-emerald" />} label="CO₂" value={`${v.co2?.toFixed(2)} kg`} />
                <KV icon={<Leaf className="h-3 w-3 text-neon-emerald" />} label="Fuel" value={`${v.fuel?.toFixed(2)} L`} />
                <KV icon={<Brain className="h-3 w-3 text-neon-cyan" />} label="Travel" value={`${v.travel?.toFixed(1)}s`} />
              </div>
            </div>
          );
        })}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Section title="Congestion & Queue Forecast" subtitle="trajectory across horizons" icon={TrendingUp}>
          <LineChartM
            data={data}
            series={[
              { k: "congestion", color: "#8b5cf6" },
              { k: "queue", color: "#22e0ff" },
            ]}
          />
        </Section>
        <Section title="CO₂ + Fuel Outlook" subtitle="emissions per horizon" icon={Leaf}>
          <BarSeries data={data} x="horizon" y="co2" color="#22d3a5" />
        </Section>
        <Section title="Radar Projection" subtitle="10-minute holistic view" icon={Brain}>
          <RadarBundle data={radar} height={220} />
        </Section>
      </div>

      <Section title="Prediction confidence vs horizon" subtitle="confidence decays with horizon length">
        <BarSeries
          data={data.map((d) => ({ horizon: d.horizon, value: Math.round((p[d.horizon]?.confidence ?? 0) * 100) }))}
          x="horizon" y="value" color="#22e0ff" height={200}
        />
      </Section>
    </div>
  );
}

function KV({ icon, label, value }) {
  return (
    <div className="flex items-center justify-between">
      <span className="flex items-center gap-1.5 text-slate-400">{icon}{label}</span>
      <span className="text-white font-mono">{value}</span>
    </div>
  );
}

function Confidence({ value }) {
  const pct = Math.round(value * 100);
  if (!pct) return <span className="text-slate-400">—</span>;
  const tone = pct >= 70 ? "text-neon-emerald" : pct >= 45 ? "text-neon-amber" : "text-neon-rose";
  return <span className={tone}>{pct}%</span>;
}
